FROM python:3.10.9 

WORKDIR /app  

# Copy the djangorequirements.txt file from the current directory
COPY djangorequirements.txt /app/requirements.txt

RUN pip install -r requirements.txt  

# Copy the django-app contents
COPY . /app

WORKDIR /app/myapp

#RUN python myapp/manage.py collectstatic --noinput

EXPOSE 8002
CMD ["gunicorn", "--config", "../django_guni_config.py", "myapp.wsgi:application"]