FROM python:3.10.9 

WORKDIR /django-app  

# Copy the djangorequirements.txt file from the current directory
COPY djangorequirements.txt /django-app/requirements.txt

RUN pip install -r requirements.txt  

# Copy the django-app contents
COPY . /django-app

# Remove the WORKDIR change, as it's already set to /django-app
# WORKDIR /django-app/myapp

EXPOSE 8000
CMD ["gunicorn", "--config", "django_guni_config.py", "myapp.wsgi:application"]