name: CD

on:
  push:
    branches: 
    - main 

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Django App Docker Image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/django-app:latest -f django-app/Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/django-app:latest

    - name: Build and Push LLM API Docker Image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/llm-api:latest -f llm-api/Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/llm-api:latest

    - name: Build and Push DB API Docker Image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/db-api:latest -f db-api/Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/db-api:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy LLM API to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.AZ_RESOURCE_GROUP }}
        dns-name-label: mrowell-llm-api
        image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/llm-api:latest
        registry-login-server: docker.io
        registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
        registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}
        name: mrowell-llm-api
        location: ${{ secrets.AZ_LOCATION }}
        ports: '8001'
        secure-environment-variables: |
          DB_API_TOKEN=${{ secrets.DB_API_TOKEN }}
          DB_API_URL=${{ secrets.DB_API_URL }}
          OLLAMA_MODEL=${{ secrets.OLLAMA_MODEL }}
          ADMIN_TOKEN=${{ secrets.ADMIN_TOKEN }}

    - name: Deploy DB API to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.AZ_RESOURCE_GROUP }}
        dns-name-label: mrowell-db-api
        image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/db-api:latest
        registry-login-server: docker.io
        registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
        registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}
        name: mrowell-db-api
        location: ${{ secrets.AZ_LOCATION }}
        ports: '8000'
        secure-environment-variables: |
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_API_TOKEN=${{ secrets.DB_API_TOKEN }}
          DB_API_URL=${{ secrets.DB_API_URL }}

    - name: Deploy Django App to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.AZ_RESOURCE_GROUP }}
        dns-name-label: mrowell-django-app
        image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/django-app:latest
        registry-login-server: docker.io
        registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
        registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}
        name: mrowell-django-app
        location: ${{ secrets.AZ_LOCATION }}
        ports: '8002'
        secure-environment-variables: |
          DB_SERVER=${{ secrets.DB_SERVER }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DJANGO_USE_DATABASE=${{ secrets.DJANGO_USE_DATABASE }}
          DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }}
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
